import { readdir, mkdir, writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';

// Only repository-authored MDX is compiled. Never load MDX from user input or a remote URL.
const collections = ['applications', 'demonstrations', 'articles'];
const imports = [];
const entries = [];
for (const collection of collections) {
  const directory = path.join(process.cwd(), 'content', collection);
  await mkdir(directory, { recursive: true });
  const files = (await readdir(directory)).filter((file) => file.endsWith('.mdx')).sort();
  for (const file of files) {
    const slug = file.slice(0, -4);
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))
      throw new Error(`Invalid content filename: ${file}`);
    const id = `entry${entries.length}`;
    imports.push(
      `import ${id}, { frontmatter as ${id}Metadata } from '../../content/${collection}/${file}';`,
    );
    entries.push(
      `  { collection: '${collection}', slug: '${slug}', metadata: ${id}Metadata, Content: ${id} }`,
    );
  }
}
await mkdir('src/generated', { recursive: true });
await writeFile(
  'src/generated/content-registry.ts',
  `// Generated by scripts/generate-content.mjs. Do not edit.\n${imports.join('\n')}\n\nexport const contentRegistry = [\n${entries.join(',\n')}\n] as const;\n`,
);
console.log(`Discovered ${entries.length} MDX documents.`);

const css = await readFile('src/styles/tokens.css', 'utf8');
const tokens = Object.fromEntries(
  [...css.matchAll(/(--[a-z0-9-]+):\s*([^;]+);/g)].map((match) => [match[1], match[2].trim()]),
);
await writeFile(
  'src/generated/design-tokens.ts',
  `// Generated from src/styles/tokens.css. Do not edit.\nexport const designTokens = ${JSON.stringify(tokens, null, 2)} as const;\n`,
);
